<?php /** @var Spotlight $this */

use components\layout\Spotlight\Spotlight;
use core\sideloader\importers\Css\Css;
use core\sideloader\importers\Javascript\Javascript;
use core\view\Html;

Css::importDefault($this);
Javascript::importDefault($this);

?><div class="spotlight">
    <?php foreach ($this->views as $label => $view): ?>
        <div
            class="spotlight-item <?= $this->visibilityClass($label) ?>"
            data-spotlight-item="<?= Html::escapeAttribute($label) ?>"
        >
            <?= $view ?>
        </div>
    <?php endforeach; ?>
</div>
