<?php /** @var HeaderSearch $this */

use components\core\Icon;
use components\core\Search\HeaderSearch;
use core\sideloader\importers\Css\Css;
use core\sideloader\importers\Javascript\Javascript;

Css::import($this->getResource('header-search.css'));
Javascript::import($this->getResource('search.js'));

?><div
    class="header-search"
    x-init="search_headerSearch"
    <?php if (!is_null($this->url)): ?>
        data-url="<?= $this->url ?>"
    <?php endif; ?>
    data-min-length="<?= $this->minLength ?>"
>
    <div class="header-search-form">
        <input
            id="header-search"
            class="header-search-input"
            type="search"
            name="q"
            placeholder="<?= $this->tr($this->placeholder) ?>"
            autocomplete="off"
        >

        <label class="header-search-button" for="header-search">
            <?= Icon::nf('nf-fa-search') ?>
        </label>
    </div>

    <div class="header-search-dropdown">
        <div class="search-empty">
            <?= $this->tr('No results found') ?>
        </div>
    </div>
</div>