<?php /** @var TextArea $this */

use modules\forms\controls\TextArea\TextArea;

?>
<?php $id = $this->getId() ?>
<div class="form-control <?= $this->cssClass ?>">
    <label for="<?= $id ?>"><?= $this->label ?></label>
    <textarea
        id="<?= $id ?>"
        name="<?= $this->name ?>"
        id="<?= $id ?>"
        <?= $this->getHtmlAttributes() ?>
    ><?= $this->value ?></textarea>
</div>