<?php /** @var \core\forms\controls\Input\Input $this */

use core\forms\controls\Input\Input;

?>
<?php $id = $this->getId() ?>
<div class="form-control <?= $this->cssClass ?>">
    <?php if (!is_null($this->label)): ?>
        <label for="<?= $id ?>"><?= $this->label ?></label>
    <?php endif; ?>
    <input
        type="<?= $this->type ?>"
        value="<?= $this->value ?>"
        name="<?= $this->name ?>"
        id="<?= $id ?>"
        <?= $this->stringifyAttributes() ?>
    >
</div>
