<?php /** @var Accordion $this */

use components\layout\Accordion\Accordion;
use modules\SideLoader\Css;
use modules\SideLoader\Javascript;

Css::import($this->getResource('accordion.css'));
Javascript::import($this->getResource('accordion.js'));

?>
<div
    class="accordion"
    x-init="accordion"
    data-is-expanded="<?= $this->isExpanded ?>"
>
    <div class="title">
        <?= $this->title ?>
    </div>

    <div class="content">
        <?= $this->content ?>
    </div>
</div>
