<?php /** @var DashboardPageView $this */

use components\Dashboard\DashboardPageView;
use core\sideloader\importers\Css\Css;

Css::importDefault($this);

?><!DOCTYPE html>
<html lang="<?= $this->head->getLanguageCode() ?>">
<?= $this->head ?>

<body>
    <div class="root dashboard-page">
        <?= $this->dashboard->getSideBar() ?>

        <main>
            <?= $this->view ?>
        </main>
    </div>
</body>
</html>