<?php

namespace core\database\pdo\column;

class PrimaryKey implements Column {
    public function __construct(
        protected bool $isAutoGenerated = false
    ) {}



    public function transform(mixed $value): mixed {
        return $value;
    }

    public function isVirtual(): bool {
        return false;
    }

    public function isAutoCreated(): bool {
        return $this->isAutoGenerated;
    }
}