<?php /** @var \components\core\HtmlHead\HtmlHead $this */

use modules\SideLoader\SideLoader; ?>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <?php foreach ($this->meta as $name => $content): ?>
        <meta name="<?= $name ?>" content="<?= $content ?>">
    <?php endforeach; ?>

    <title><?= $this->title ?></title>

    <?= SideLoader::getInstance() ?>
</head>