<?php /** @var HtmlHead $this */

use components\core\FrontEndCore\FrontEndCore;
use components\core\HtmlHead\HtmlHead;
use components\core\jsml\Jsml;
use core\App;
use core\route\Path;
use core\sideloader\SideLoader;

?>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="icon" type="image/x-icon" href="<?= App::getInstance()->attach(Path::from("/public/images/favicon.png")) ?>">

    <?php foreach ($this->meta as $name => $content): ?>
        <meta name="<?= $name ?>" content="<?= $content ?>">
    <?php endforeach; ?>

    <title><?= $this->title ?></title>

    <?= new FrontEndCore() ?>
    <?= Jsml::getInstance() ?>
    <?= SideLoader::getApi() ?>
    <?= SideLoader::getInstance() ?>

    <?php foreach ($this->elements as $element): ?>
        <?= $element ?>
    <?php endforeach; ?>
</head>