<?php /** @var \components\Admin\Nexus\AdminNexus $this */

use components\Admin\Nexus\AdminNexus;
use core\sideloader\importers\Css\Css;
use core\sideloader\importers\Javascript\Javascript;
use core\view\Html;

Javascript::importDefault($this);
Css::importDefault($this);

?><section class="nexus">
    <?php if ($this->showHeader): ?>
        <div class="head">
            <h1><?= Html::escape($this->getTitle()) ?></h1>

            <?php if ($this->canShowCreateButton()): ?>
                <a class="button" href="<?= $this->getCreateLink() ?>">
                    <?= Html::escape($this->createButtonLabel) ?>
                </a>
            <?php endif; ?>

            <?= $this->getTemplateSlot(AdminNexus::SLOT_HEADER_ITEM) ?>
        </div>
    <?php endif; ?>

    <?= $this->getTemplateSlot(AdminNexus::SLOT_BREAD_CRUMBS) ?>

    <?= $this->getGrid() ?>

    <?= $this->getTemplateSlot(AdminNexus::SLOT_FOOTER) ?>
</section>
