<?php /** @var Article $this */

use components\core\Html\Html;
use components\core\Markdown\Markdown;
use components\pages\Article\Article;
use core\sideloader\importers\Css\Css;
use core\sideloader\importers\Javascript\Javascript;

Markdown::importAssets();
Javascript::import($this->getResource('article.js'));
Css::import($this->getResource('article.css'));

?><div class="page" x-init="article">
    <pre id="data-content" class="display-none"><?= Html::escape($this->content) ?></pre>

    <aside class="article-toc-wrapper">
        <div class="article-toc-container">
            <h3><?= $this->tr("Table of Contents") ?></h3>

            <div class="article-toc-content"></div>
        </div>
    </aside>

    <article class="article">
        <section class="article-content"></section>
    </article>
</div>