<?php /** @var \modules\forms\controls\MultiSubmit\MultiSubmit $this */ ?>
<div class="form-actions">
    <?php foreach ($this->actions as $action): ?>
        <button
            type="<?= $action->type ?>"
            <?php if ($action->action !== ""): ?>
                data-action="<?= $action->action ?>"
            <?php endif; ?>
        ><?= $action->label ?></button>
    <?php endforeach; ?>
</div>
