<?php /** @var \components\core\Admin\Menu\Item\AdminMenuItem $this */ ?>
<div class="item-label">
    <?php $icon = $this->getIcon() ?>
    <?php if ($icon !== ''): ?>
        <span class="icon">
            <?= $icon ?>
        </span>
    <?php endif; ?>

    <?php if ($this->hasValue): ?>
        <a href="<?= $this->createUrl() ?>">
            <?= $this->label ?>
        </a>
    <?php else: ?>
        <span><?= $this->label ?></span>
    <?php endif; ?>
</div>
