<?php /** @var FrontEndCore $this */

use components\core\FrontEndCore\FrontEndCore;
use core\sideloader\Css;
use core\sideloader\Javascript;
use core\sideloader\SideLoader;

?>
<?php if (SideLoader::getInstance()->isInitialized()): ?>
    <script
        <?= SideLoader::getInstance()
            ->createSourceAttribute(
                Javascript::FILE_TYPE,
                $this->getPublicSources('js', '*.js')
            ) ?>
    ></script>

    <link
        rel="stylesheet"
        <?= SideLoader::getInstance()
            ->createSourceAttribute(
                Css::FILE_TYPE,
                $this->getPublicSources('css', '*.css'),
                'href'
            ) ?>
    >
<?php endif; ?>
