<?php /** @var Accordion $this */

use components\layout\Accordion;
use core\sideloader\importers\Css\Css;
use core\sideloader\importers\Javascript\Javascript;
use core\view\Html;

Css::importDefault($this);
Javascript::importDefault($this);

?><div
    class="accordion"
    x-init="accordion_init"
    data-is-expanded="<?= $this->isExpanded ?>"
>
    <div class="title">
        <?= Html::escape($this->title) ?>
    </div>

    <div class="content">
        <div class="content-resize-detector">
            <?= $this->content ?>
        </div>
    </div>
</div>
