<?php /** @var ExpectationMessage $this */

use components\tf\ExpectationMessage;
use core\view\Html;

?><div>
    <div class='index'>
        <?= Html::escape($this->hint) ?>
    </div>

    <div class='expected'>
        <?= Html::escape($this->tr('Expected')) ?>: <?= Html::escape(json_encode($this->expected)) ?>
    </div>

    <div class='actual'>
        <?= Html::escape($this->tr('Got')) ?>: <?= Html::escape(json_encode($this->actual)) ?>
    </div>
</div>