<?php /** @var WebPage $this */

use components\core\WebPage\WebPage;

?><!DOCTYPE html>
<html lang="<?= $this->language ?>">
    <?= $this->head ?>
    <body>
        <div class="root">
            <main>
                <?php foreach ($this->children as $child): ?>
                    <?= $child->render() ?>
                <?php endforeach; ?>
            </main>
        </div>
    </body>
</html>