<?php /** @var WebPage $this */

use components\core\Admin\Home\AdminHome;
use components\core\Admin\Menu\AdminMenu;
use components\core\Admin\Project\AdminProject;
use components\core\Terminal\Terminal;
use components\core\WebPage\WebPage;
use modules\SideLoader\Css;

Css::import($this->getResource('admin-page.css'));

?>
<!DOCTYPE html>
<html lang="<?= $this->language ?>">
<?= $this->head ?>
<body class="admin-page">
    <?= Terminal::getInstance() ?>

    <nav>
        <?= new AdminProject() ?>
        <?= AdminMenu::getInstance() ?>

        <div
            class="resize-handle"
            data-target="<parent>"
            data-direction="horizontal"
        ></div>
    </nav>

    <main>
        <section>
            <?php $crumbs = AdminHome::changeHomeLabel(AdminMenu::getBreadCrumbs()) ?>
            <?php if (count($crumbs->getItems()) > 1): ?>
                <?= $crumbs->render() ?>
            <?php endif; ?>
        </section>

        <?php foreach ($this->children as $child): ?>
            <?= $child->render() ?>
        <?php endforeach; ?>
    </main>
</body>
</html>