<?php /** @var WebPage $this */

use components\core\Admin\Menu\AdminMenu;
use components\core\WebPage\WebPage;
use core\App;
use core\endpoints\AdminEndpoint;
use modules\SideLoader\Css;

Css::import($this->getSource('admin-page.css'));
$app = App::getInstance();

?>
<!DOCTYPE html>
<html lang="<?= $this->language ?>">
<?= $this->head ?>
<body class="admin-page">
    <nav>
        <?php if (!is_null($project = $app->getProjectName())): ?>
            <div class="project">
                <h2>
                    <a
                        class="home-link"
                        href="<?= $app->prependHome(AdminEndpoint::getInstance()->getPath()) ?>"
                    ><?= $project ?></a>
                </h2>
                <?php if (!is_null($author = $app->getProjectAuthor())): ?>
                    <span class="author">by <?= $author ?></span>
                <?php endif; ?>
            </div>
        <?php endif; ?>
        <?= AdminMenu::getInstance() ?>
    </nav>
    <main>
        <?php foreach ($this->children as $child): ?>
            <?= $child->render() ?>
        <?php endforeach; ?>
    </main>
</body>
</html>