<?php /** @var Header $this */

use components\core\Icon;
use components\core\PageMenu\Header;
use components\core\Search\HeaderSearch;
use components\core\Window\Window;
use components\windows\LanguageSelect\LanguageSelect;
use core\sideloader\importers\Css\Css;

Css::import($this->getResource('header.css'));

?><header>
    <div class="header-items">
        <?= $this->menu ?>

        <div class="row">
            <?= new HeaderSearch() ?>

            <?= $languageWindow = LanguageSelect::window(false) ?>
            <?= Window::createWindowOpener(
                $languageWindow,
                Icon::nf('nf-fa-language', 'Languages'),
                ['style' => 'font-size: 2rem; padding: unset', 'class' => 'link no-decoration']
            ) ?>
        </div>
    </div>
</header>