<?php /** @var BreadCrumbs $this */

use components\core\BreadCrumbs\BreadCrumbs;
use core\sideloader\importers\Css\Css;

$count = count($this->items);

if ($count > 0) {
    Css::import($this->getResource('bread-crumbs.css'));
}

?>
<?php if ($count > 0): ?>
    <ul class="bread-crumbs">
        <?php $first = true; foreach ($this->items as $item): ?>
            <?php if (!$first && !is_null($this->delimitor)): ?>
                <li class="delimitor"><?= $this->delimitor ?></li>
            <?php endif; ?>

            <?= $item ?>
        <?php $first = false; endforeach; ?>
    </ul>
<?php endif; ?>
