<?php /** @var BreadCrumbs $this */

use components\core\BreadCrumbs\BreadCrumbs;
use core\sideloader\Css;

$count = count($this->items);

if ($count > 0) {
    Css::import($this->getResource('bread-crumbs.css'));
}

?>
<?php if ($count > 0): ?>
    <ul class="bread-crumbs">
        <?php $first = true; foreach ($this->items as $item): ?>
            <?php if (!$first): ?>
                <li class="delimitor"><?= $this->delimitor ?></li>
            <?php endif; ?>

            <li class="bread-crumb">
                <?php if (is_null($item->getUrl())): ?>
                    <span><?= $item->getLabel() ?></span>
                <?php else: ?>
                    <a href="<?= $item->getUrl() ?>"><?= $item->getLabel() ?></a>
                <?php endif; ?>
            </li>
        <?php $first = false; endforeach; ?>
    </ul>
<?php endif; ?>
