<?php /** @var BreadCrumbs $this */

use components\core\BreadCrumbs\BreadCrumbs;
use modules\SideLoader\Css;

$count = count($this->items);

if ($count > 0) {
    Css::import($this->getSource('bread-crumbs.css'));
}

?>
<?php if ($count > 0): ?>
    <ul class="bread-crumbs">
        <?php $first = true; foreach ($this->items as $item): ?>
            <?php if (!$first): ?>
                <span class="delimitor"><?= $this->delimitor ?></span>
            <?php endif; ?>
            <?= $item->render() ?>
        <?php $first = false; endforeach; ?>
    </ul>
<?php endif; ?>
