<?php /** @var PasswordField $this */

use components\core\Icon;
use core\forms\controls\PasswordField\PasswordField;

$id = $this->getId();

?><div class="form-control <?= $this->cssClass ?>" x-init="form_password">
    <label for="<?= $id ?>"><?= $this->getLabel() ?></label>
    <div class="password-container">
        <input
            type="password"
            value="<?= $this->getValue() ?>"
            name="<?= $this->getFieldName() ?>"
            id="<?= $id ?>"
            <?= $this->stringifyAttributes() ?>
        >
        <?php if ($this->addVisibilityControl): ?>
            <div class="password-visibility-control">
                <button data-action="show">
                    <?= Icon::nf('nf-fa-eye', 'Show') ?>
                </button>
                <button class="hide" data-action="hide">
                    <?= Icon::nf('nf-fa-eye_slash', 'Hide') ?>
                </button>
            </div>
        <?php endif; ?>
    </div>
</div>
