<?php /** @var Index $this */

use components\core\Resource\Index;
use components\resources\Cards\Cards;
use core\Resource;
use tables\Card;

?><div class="cards">
    <?php $base = Cards::getInstance()->getUrl(Resource::URL_READ) ?>
    <?php foreach ($this->models as $model): ?>
        <?php /** @var Card $model */ ?>
        <a href="<?= Cards::getInstance()->createUrl($model, $base) ?>">
            <div class="card">
                <span class="question"><?= $model->question ?></span>
                <span class="answer"><?= $model->answer ?></span>
            </div>
        </a>
    <?php endforeach; ?>
</div>