<?php /** @var \modules\forms\controls\PasswordField\PasswordField $this */ ?>
<?php $id = $this->field->getId() ?>
<div class="form-control <?= $this->cssClass ?>" x-init="form_password">
    <label for="<?= $id ?>"><?= $this->field->getLabel() ?></label>
    <div class="password-container">
        <input
            type="password"
            value="<?= $this->field->getValue() ?>"
            name="<?= $this->field->getFieldName() ?>"
            id="<?= $id ?>"
            <?= $this->stringifyAttributes() ?>
        >
        <?php if ($this->addVisibilityControl): ?>
            <div class="password-visibility-control">
                <button data-action="show">
                    <?= \components\core\Icon::nf('nf-fa-eye') ?>
                </button>
                <button class="hide" data-action="hide">
                    <?= \components\core\Icon::nf('nf-fa-eye_slash') ?>
                </button>
            </div>
        <?php endif; ?>
    </div>
</div>
