<?php /** @var AdminNexus $this */

use components\core\Admin\Nexus\AdminNexus;
use core\sideloader\Css;
use core\sideloader\Javascript;

Javascript::import($this->getResource('nexus.js'));
Css::import($this->getResource('nexus.css'));

?>
<section class="nexus">
    <div class="head">
        <h1><?= $this->getTitle() ?></h1>

        <?php if ($this->showCreateButton): ?>
            <a class="button" href="<?= $this->getCreateLink() ?>"><?= $this->createButtonLabel ?></a>
        <?php endif; ?>
    </div>

    <?php if (!is_null($this->breadCrumbs)): ?>
        <?= $this->breadCrumbs ?>
    <?php endif; ?>

    <?= $this->getGrid() ?>
</section>
