<?php /** @var AdminNexus $this */

use components\core\Admin\Nexus\AdminNexus;
use modules\SideLoader\Javascript;

Javascript::import($this->getResource('nexus.js'));

?>
<section>
    <h1><?= $this->getTitle() ?></h1>

    <a class="button" href="<?= $this->getCreateLink() ?>">Create</a>
    <a class="button" href="<?= $this->getUpdateLink('4') ?>">Update</a>
    <a class="button" href="<?= $this->getDeleteLink('4') ?>">Delete</a>

    <?= $this->getTable() ?>
</section>
