<?php /** @var AdminNexus $this */

use components\core\Admin\Nexus\AdminNexus;
use core\sideloader\importers\Css\Css;
use core\sideloader\importers\Javascript\Javascript;

Javascript::import($this->getResource('nexus.js'));
Css::import($this->getResource('nexus.css'));

?>
<section class="nexus">
    <?php if ($this->showHeader): ?>
        <div class="head">
            <h1><?= $this->getTitle() ?></h1>

            <?php if ($this->canShowCreateButton()): ?>
                <a class="button" href="<?= $this->getCreateLink() ?>"><?= $this->createButtonLabel ?></a>
            <?php endif; ?>

            <?php if (!is_null($this->headerContent)): ?>
                <?= $this->headerContent ?>
            <?php endif; ?>
        </div>
    <?php endif; ?>

    <?php if (!is_null($this->breadCrumbs)): ?>
        <?= $this->breadCrumbs ?>
    <?php endif; ?>

    <?= $this->getGrid() ?>
</section>
