<?php /** @var NotFound $this */

use components\Message\Message;
use components\NotFound;
use core\view\Html;

?><div class="page-container">
    <div class="page-section column">
        <?= new Message($this->createTitle()) ?>

        <div>
            <button onclick="history.back()">
                <?= Html::escape($this->tr('Go back')) ?>
            </button>
        </div>
    </div>
</div>