<?php

namespace components\pages\AiGeneratedPage;

use components\core\Admin\Nexus\Editor\EditorBehavior;
use components\core\Message\Message;
use components\pages\Wireframe\Wireframe;
use core\actions\Action;
use core\forms\description\FormDescription;
use core\pages\PagePreview;
use core\pages\PageTemplate;
use core\view\Component;
use core\view\View;
use models\core\Page\AiPage;
use models\core\Page\Page;

class AiPageTemplate implements PageTemplate {
    use PagePreview;

    public const DATA_ITEM_HTML = 'html';
    public const DATA_ITEM_JS = 'js';
    public const DATA_ITEM_CSS = 'css';



    public function getName(): string {
        return "AI Generated";
    }

    public function getDescription(): string {
        return "Static page generated by AI from a single user prompt. Includes editor to view and edit page sources";
    }

    public function create(Page $page): ?View {
        $aiPage = new AiPage();

        $aiPage->pageId = $page->id;
        $aiPage->prompt = '';
        $aiPage->save();

        return null;
    }

    public function delete(Page $page): ?View {
        AiPage::fromPage($page)?->delete();

        $page
            ->get(self::DATA_ITEM_HTML)
            ->delete();

        $page
            ->get(self::DATA_ITEM_JS)
            ->delete();

        $page
            ->get(self::DATA_ITEM_CSS)
            ->delete();

        return null;
    }

    public function hasEditor(): bool {
        return false;
    }

    public function buildEditor(Page $page): Action {
        return new Message('AI Generated Page has no content editor associated with its template');
    }

    public function buildEditorBehavior(): ?EditorBehavior {
        return new AiPageEditorBehavior(
            FormDescription::extract(AiPage::class),
            $this
        );
    }

    public function buildContent(Wireframe $wireframe, Page $page): Component {
        return AiGeneratedPage::build($wireframe, $page);
    }
}