<?php /** @var File $this */

use core\forms\controls\File\File;

?><label class="form-file" x-init="form_file">
    <span>Drag and drop files, or click to select</span>

    <input
        class="hide"
        type="<?= $this->type ?>"
        name="<?= $this->name ?>"
        id="<?= $this->getId() ?>"
        <?= $this->stringifyAttributes() ?>
    >

    <span class="form-files">
        <?php foreach ($this->files as $file): ?>
            <div class="tag">
                <span><?= $file ?></span>
                <button>✕</button>
            </div>
        <?php endforeach; ?>
    </span>
</label>
