<?php /** @var SptfTests $this */

use components\Admin\SptfTests\SptfTests;
use core\sideloader\importers\Css\Css;
use core\sideloader\importers\Javascript\Javascript;

Css::importDefault($this);
Javascript::importDefault($this);

?><section>
    <button x-init="sptf_hideButton">Hide passed tests</button>
</section>

<section class="sptf">
    <?php foreach ($this->getTestFiles() as $test): ?>
        <?= $test ?>
    <?php endforeach; ?>
</section>
