<?php /** @var SptfTestFile $this */

use components\core\Admin\SptfTests\SptfTestFile;

?><div
    class="test-file"
    data-failed="<?= $this->testFile->getFailed() ?>"
    data-passed="<?= $this->testFile->getPassed() ?>"
>
    <div class="test-file-head">
        <span class="passed"><?= $this->testFile->getPassed() ?></span>
        <span class="failed"><?= $this->testFile->getFailed() ?></span>
        <span class="file"><?= $this->testFile->getFile() ?></span>
    </div>

    <div>
        <?php foreach ($this->testFile->getSuites() as $suite): ?>
            <?php $outcome = $suite->getOutcome(); ?>
            <div class="suite <?= strtolower($outcome->value) ?>">
                <div class="suite-head ">
                    <span class="outcome"><?= $outcome->value ?></span>
                    <span class="time"><?= sprintf("%.02f s", $suite->getTime()) ?></span>
                    <span class="name"><?= $suite->getName() ?></span>
                    <span class="stats">
                        <?php $passed = $suite->getPassed() ?>
                        <?php $failed = $suite->getFailed() ?>
                        <?php if ($passed !== 0): ?>
                            <span class="passed"><?= $passed ?>P</span>
                        <?php endif; ?>
                        <?php if ($passed !== 0 && $failed !== 0): ?>/<?php endif; ?>
                        <?php if ($failed !== 0): ?>
                            <span class="failed"><?= $failed ?>F</span>
                        <?php endif; ?>
                        <?php if ($passed !== 0 || $failed !== 0): ?>assertions<?php endif; ?>
                    </span>
                </div>

                <div class="suite-assertions">
                    <?php foreach ($suite->getAssertions() as $assertion): ?>
                        <?php if (!$assertion->result()): ?>
                            <div class="assertion failed">
                                <?= $assertion->error()->html() ?>
                            </div>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </div>

                <div class="suite-output">
                    <?= $suite->getOutput() ?>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</div>
