<?php /** @var \components\Home\Home $this */

use modules\locales\EnglishUS;

?><h1>Route Chasm</h1>
<a href="https://github.com/CaptSiro/route-chasm">GitHub repository</a>

<p>Navigate to <code>src/components/Home/Home.phtml</code> to edit this page</p>

<hr>
<h3>Languages</h3>
<span><?= $this->tr('home', 'Selected') ?>: <?= \core\App::getInstance()->getRequest()->getLanguage()->getLocale()->getName() ?></span>
<?php foreach (\core\App::getInstance()->getLocales() as $locale): ?>
    <div>
        <?= $this->createLanguageLink($locale) ?>
    </div>
<?php endforeach; ?>

<div><?= $this->trt('home', '{} flowers', 0, templates: EnglishUS::pluralize('{} flower', '{} flowers')) ?></div>
<div><?= $this->trt('home', '{} flowers', 1, templates: EnglishUS::pluralize('{} flower', '{} flowers')) ?></div>
<div><?= $this->trt('home', '{} flowers', 2, templates: EnglishUS::pluralize('{} flower', '{} flowers')) ?></div>
<div><?= $this->trt('home', '{} flowers', 3, templates: EnglishUS::pluralize('{} flower', '{} flowers')) ?></div>
<div><?= $this->trt('home', '{} flowers', 4, templates: EnglishUS::pluralize('{} flower', '{} flowers')) ?></div>
<div><?= $this->trt('home', '{} flowers', 5, templates: EnglishUS::pluralize('{} flower', '{} flowers')) ?></div>
