<?php /** @var Home $this */

use components\core\fs\FileControl;
use components\Home\Home;
use core\fs\variants\ImageVariant;
use modules\locales\EnglishUS;



$md1 = "

### Unordered

* Item 1
* Item 2
* Item 2a
* Item 2b
    * Item 3a
    * Item 3b

### Ordered

1. Item 1
2. Item 2
3. Item 3
    1. Item 3a
    2. Item 3b
    
## Images

![This is an alt text.](/image/Markdown-mark.svg \"This is a sample image.\")

## Links

You may be using [Markdown Live Preview](https://markdownlivepreview.com/).

## Blocks of code

```
let message = 'Hello world';
alert(message);
```

";

$md = "
# Markdown syntax guide

## Headers

# This is a Heading h1
## This is a Heading h2
###### This is a Heading h6

## Emphasis

*This text will be italic*  
_This will also be italic_

**This text will be bold**  
__This will also be bold__

_You **can** combine them_

## Lists

### Unordered

* Item 1
* Item 2
* Item 2a
* Item 2b

### Ordered

1. Item 1
2. Item 2
3. Item 3

## Images

![This is an alt text.](https://picsum.photos/300/50 \"This is a sample image.\")

## Links

You may be using [Markdown Live Preview](https://markdownlivepreview.com/).

## Blockquotes

> Markdown is a lightweight markup language
>> Markdown is often used to format readme

## Tables

| Left columns  | Right columns |
| ------------- |:-------------:|
| left foo      | right foo     |
| left bar      | right bar     |
| left baz      | right baz     |

## Blocks of code

```
let message = 'Hello world';
alert(message);
```

## Inline code

This web site is using `markedjs/marked`.
"

?><h1>Route Chasm</h1>
<a href="https://github.com/CaptSiro/route-chasm">GitHub repository</a>

<p>Navigate to <code>src/components/Home/Home.phtml</code> to edit this page</p>

<?= new \components\core\MarkDown\MarkDown($md) ?>

<!--<hr>-->
<!--<h3>Languages</h3>-->
<!--<span>--><?php //= $this->trg('home', 'Selected') ?><!--: --><?php //= \core\App::getInstance()->getRequest()->getLanguage()->getLocale()->getName() ?><!--</span>-->
<?php //foreach (\core\App::getInstance()->getLocales() as $locale): ?>
<!--    <div>-->
<!--        --><?php //= $this->createLanguageLink($locale) ?>
<!--    </div>-->
<?php //endforeach; ?>
<!---->
<!--<div>-->
<!---->
<!--    --><?php //= $this->trtg('home', '{} flowers', 0,
//        templates: EnglishUS::pluralize('{} flower', '{} flowers')) ?>
<!---->
<!--</div>-->
<!--<div>--><?php //= $this->trtg('home', '{} flowers', 1, templates: EnglishUS::pluralize('{} flower', '{} flowers')) ?><!--</div>-->
<!--<div>--><?php //= $this->trtg('home', '{} flowers', 2, templates: EnglishUS::pluralize('{} flower', '{} flowers')) ?><!--</div>-->
<!--<div>--><?php //= $this->trtg('home', '{} flowers', 3, templates: EnglishUS::pluralize('{} flower', '{} flowers')) ?><!--</div>-->
<!--<div>--><?php //= $this->trtg('home', '{} flowers', 4, templates: EnglishUS::pluralize('{} flower', '{} flowers')) ?><!--</div>-->
<!--<div>--><?php //= $this->trtg('home', '{} flowers', 5, templates: EnglishUS::pluralize('{} flower', '{} flowers')) ?><!--</div>-->
<!---->
<!---->
<!---->
<?php //$file = \models\core\fs\File::fromId(5) ?>
<!--<img src="--><?php //= $file->getUrl(ImageVariant::get(ImageVariant::TRANSFORMER_ARTICLE_THUMBNAIL)) ?><!--"-->
<!--     alt="hom" width="400" height="300">-->
<!--<img src="--><?php //= $file->getUrl(ImageVariant::get('article-icon')) ?><!--"-->
<!--     alt="hom" width="100" height="100">-->
<!--<img src="--><?php //= $file->getUrlToModel() ?><!--" alt="hom" width="384" height="216">-->
<!---->
<!---->
<?php //= new FileControl('image', 'Homepage Image') ?>
