<?php /** @var Form $this */

use core\forms\Form;
use modules\SideLoader\Css;
use modules\SideLoader\Javascript;

?>
<?php Javascript::import($this->getResource("form.js")); ?>
<?php Css::import($this->getResource("form.css")); ?>
<form
    class="form"
    data-method="<?= $this->method ?>"
    data-transformer="<?= $this->bodyTransformer ?>"
    <?php if (!is_null($this->action)): ?>
        action="<?= $this->action ?>"
    <?php endif; ?>
    x-init="form_init"
>
    <div class="form-barrier">
        <?php foreach ($this->elements as $control): ?>
            <?= $control->render() ?>
        <?php endforeach; ?>
    </div>
</form>
