<?php /** @var \core\forms\Form $this */

use core\forms\Form;
use modules\SideLoader\Css;
use modules\SideLoader\Javascript;

?>
<?php Javascript::import($this->getResource("form.js")); ?>
<?php Css::import($this->getResource("form.css")); ?>
<form
    class="form"
    data-method="<?= $this->method ?>"
    data-transformer="<?= $this->bodyTransformer ?>"
    <?php if (!is_null($this->action)): ?>
        action="<?= $this->action ?>"
    <?php endif; ?>
    onsubmit="form_submit(this); return false"
>
    <?php foreach ($this->elements as $control): ?>
        <?= $control->render() ?>
    <?php endforeach; ?>
</form>
