<?php /** @var Form $this */

use core\forms\Form;
use core\sideloader\importers\Css\Css;
use core\sideloader\importers\Javascript\Javascript;

?>
<?php Javascript::import($this->getResource("form.js")); ?>
<?php Css::import($this->getResource("form.css")); ?>
<form
    class="form <?= $this->getCssClass() ?>"
    data-method="<?= $this->method ?>"
    data-transformer="<?= $this->bodyTransformer ?>"
    <?php if (!is_null($this->action)): ?>
        action="<?= $this->action ?>"
    <?php endif; ?>
    <?= $this->stringifyAttributes() ?>
>
    <div class="form-barrier">
        <?php foreach ($this->elements as $control): ?>
            <?= $control->render() ?>
        <?php endforeach; ?>
    </div>
</form>
