<?php /** @var Wireframe $this */

use components\pages\Wireframe\Wireframe;

?><!DOCTYPE html>
<html lang="<?= $this->language ?>">
<?= $this->head ?>
<body>
    <main class="wireframe" style="height: 100%; overflow: auto">
        <?php if ($this->hasContentAccess()): ?>
            <?= $this->content ?>
        <?php else: ?>
            <div class="center">
                <h1>Page is not accessible</h1>
            </div>
        <?php endif; ?>
    </main>
</body>
</html>
