<?php /** @var WebPage $this */

use components\Admin\AdminLogin;
use components\Admin\AdminProject;
use components\Icon;
use components\layout\WebPage\WebPage;
use components\Terminal;
use components\windows\LanguageSelect;use core\admin\AdminRouter;
use core\App;
use core\sideloader\importers\Css\Css;
use core\view\Html;
use models\User\User;

Css::import($this->getResource('WebPage_admin.css'));
$request = App::getInstance()->getRequest();

?><!DOCTYPE html>
<html lang="<?= $this->language ?>">
<?= $this->head ?>
<script>
    /**
     * @param {Element} element
     */
    function adminPage_navItem(element) {
        element.addEventListener("click", () => {
            $('a', element)?.click();
            $('.target', element)?.click();
        });
    }
</script>
<body>
    <div class="root admin-page">
        <nav>
            <div class="start">
                <?= new AdminProject() ?>
                <?= AdminRouter::getInstance()->getMenu() ?>
            </div>

            <div class="end">
                <div class="nav-item" x-init="adminPage_navItem">
                <span class="icon">
                    <?= Icon::nf('nf-fa-language', '<') ?>
                </span>

                    <?= $languageWindow = LanguageSelect::window(openButton: false) ?>
                    <div class="target" onclick="window_open($('#<?= $languageWindow->getId() ?>'))">
                        <?= $this->trg(AdminRouter::LEXICON_GROUP, "Languages") ?>
                    </div>
                </div>

                <div class="nav-item" x-init="adminPage_navItem">
                <span class="icon">
                    <?= Icon::nf('nf-fa-power_off', '<') ?>
                </span>

                    <a href="<?= AdminLogin::createLogoutUrl($request->getUrl()) ?>">
                        <span><?= $this->trg(AdminRouter::LEXICON_GROUP, 'Logout') ?></span>
                        <span>(<?= Html::escape(User::fromRequest($request)->username) ?>)</span>
                    </a>
                </div>
            </div>

            <div
                class="resize-handle"
                data-target="<parent>"
                data-direction="horizontal"
            ></div>
        </nav>

        <main>
            <!--    todo    -->
            <!--        --><?php //$crumbs = AdminHome::changeHomeLabel(AdminMenu::getInstance()->getBreadCrumbs()) ?>
            <!--        --><?php //if (count($crumbs->getItems()) > 1): ?>
            <!--            <section>-->
            <!--                --><?php //= $crumbs->render() ?>
            <!--            </section>-->
            <!--        --><?php //endif; ?>

            <?php foreach ($this->children as $child): ?>
                <?= $child->render() ?>
            <?php endforeach; ?>
        </main>

        <?= Terminal::getInstance() ?>
    </div>
</body>
</html>