<?php

namespace core\database\column;

use core\database\Column;

class PrimaryKey implements Column {
    public function __construct(
        protected bool $isAutoGenerated = false
    ) {}



    public function transform(mixed $value): mixed {
        return $value;
    }

    public function isVirtual(mixed $value): bool {
        return $this->isAutoGenerated;
    }

    public function isAutoCreated(): bool {
        return $this->isAutoGenerated;
    }
}