<?php /** @var SearchResult $this */

use components\Search\SearchResult;
use core\view\Html;

?><?php if ($this->isLink): ?>
    <a href="<?= $this->value ?>" class="search-result" data-title="<?= Html::escapeAttribute($this->label) ?>">
        <div class="search-result-title">
            <?= Html::escape($this->label) ?>
        </div>

        <?php if (!is_null($this->meta)): ?>
            <div class="search-result-meta">
                <?= Html::escape($this->meta) ?>
            </div>
        <?php endif; ?>
    </a>
<?php else: ?>
    <div
        class="search-result"
        data-value="<?= Html::escapeAttribute($this->value) ?>"
        data-title="<?= Html::escapeAttribute($this->label) ?>"
    >
        <div class="search-result-title">
            <?= Html::escape($this->label) ?>
        </div>

        <?php if (!is_null($this->meta)): ?>
            <div class="search-result-meta">
                <?= Html::escape($this->meta) ?>
            </div>
        <?php endif; ?>
    </div>
<?php endif; ?>