<?php /** @var SearchResults $this */

use components\Search\SearchResults;
use core\view\Html;

?><?php if (empty($this->results)): ?>
    <div class="search-empty">
        <?= Html::escape($this->tr('No results found')) ?>
    </div>
<?php else: ?>
    <div class="search-results">
        <?php foreach ($this->results as $result): ?>
            <?= $result ?>
        <?php endforeach; ?>
    </div>

    <?php if (!is_null($this->searchFooter)): ?>
        <div class="search-footer">
            <?= $this->searchFooter ?>
        </div>
    <?php endif; ?>
<?php endif; ?>