<?php /** @var SearchResultsListing $this */

use components\layout\PageMenu\Footer;
use components\layout\PageMenu\Header;
use components\pages\Listing\Listing;
use components\Search\SearchResultsListing;
use core\App;
use core\view\Html;

Listing::importAssets();

?><?= Header::default() ?>

<div class="listing page-container">
    <h1 class="page-title"><?= $this->tr('Search results for') ?>: <?= Html::escape($this->query) ?></h1>

    <div class="article-grid">
        <?php $language = App::getInstance()->getRequest()->getLanguage() ?>
        <?php foreach ($this->factory->getModels() as $page): ?>
            <?= $page->getTemplate()->buildListingCard($page, $language) ?>
        <?php endforeach; ?>
    </div>

    <nav class="pagination">
        <?= $this->factory->createPagination() ?>
    </nav>
</div>

<?= Footer::default() ?>
