<?php /** @var Html $this */

use components\html\Html;
use core\utils\Arrays;
use core\view\View;

// Render html <tag attributes>content</tag>
// Todo condense to render function because THIS IS UNMAINTAINABLE! WHAT ARE WE DOING MAN?! This is an email...
?>
<<?= $this->tag ?> <?= Arrays::htmlEncode($this->attributes) ?>><?php if (!is_null($this->content)): ?>
<?= $this->content instanceof View ? $this->content->render() : $this->content ?>
<?php endif; ?><?php if ($this->doCloseTag): ?></<?= $this->tag ?>><?php endif; ?>
