<?php /** @var Accordion $this */

use components\layout\Accordion\Accordion;
use core\sideloader\importers\Css\Css;
use core\sideloader\importers\Javascript\Javascript;

Css::import($this->getResource('accordion.css'));
Javascript::import($this->getResource('accordion.js'));

?>
<div
    class="accordion"
    x-init="accordion_init"
    data-is-expanded="<?= $this->isExpanded ?>"
>
    <div class="title">
        <?= $this->title ?>
    </div>

    <div class="content">
        <div class="content-resize-detector">
            <?= $this->content ?>
        </div>
    </div>
</div>
