<?php /** @var PaginationControl $this */

use components\core\Pagination\PaginationControl;
use core\sideloader\importers\Css\Css;

Css::import($this->getResource('pagination-control.css'));

?><div class="pagination-control row">
    <?php if ($this->max > 1): ?>
        <?php if (!is_null($this->creator)): ?>
            <?php for ($i = 1; $i <= $this->max; $i++): ?>
                <?php if ($i === $this->current): ?>
                    <span class="current"><?= $i ?></span>
                <?php else: ?>
                    <a
                        href="<?= $this->creator->createUrl($i, $this->current, $this->max) ?>"
                    ><?= $i ?></a>
                <?php endif; ?>
            <?php endfor; ?>
        <?php else: ?>
            <?php for ($i = 1; $i <= $this->max; $i++): ?>
                <span
                <?php if ($i === $this->current): ?>
                    class="current"
                <?php endif; ?>
            ><?= $i ?></span>
            <?php endfor; ?>
        <?php endif; ?>
    <?php endif; ?>
</div>
