<?php /** @var Window $this */

use components\core\Icon;
use components\core\Window\Window;
use core\sideloader\importers\Css\Css;

Css::import($this->getResource('window.css'));

?><?php if ($this->openButton): ?>
    <button onclick="window_open($('#<?= $this->id ?>'))">Open <?= $this->title ?></button>
<?php endif; ?>
<div
    class="window hide"
    id="<?= $this->id ?>"

    <?php if ($this->hasFlag(Window::FLAG_DRAGGABLE)): ?>
        data-window-draggable="true"
    <?php endif; ?>

    <?php if ($this->hasFlag(Window::FLAG_DESTROY_ON_CLOSE)): ?>
        data-window-destroy-on-close="true"
    <?php endif; ?>

    <?= $this->stringifyAttributes() ?>
>
    <div class="head">
        <span><?= $this->title ?></span>
        <div class="controls">
            <?php if ($this->hasFlag(Window::FLAG_MINIMIZABLE)): ?>
                <button class="minimize">
                    <?= Icon::nf('nf-fa-window_minimize', '_') ?>
                </button>
            <?php endif; ?>
            <button class="close">
                <?= Icon::nf('nf-fa-close', 'X') ?>
            </button>
        </div>
    </div>

    <div class="content">
        <?= $this->content->getRoot()->render() ?>
    </div>
</div>
