<?php /** @var AdminPageView $this */

use components\Admin\AdminLogin;
use components\Admin\AdminProject;
use components\Icon;
use components\Admin\AdminPageView;
use components\Terminal;
use components\windows\LanguageSelect;use core\admin\AdminRouter;
use core\App;
use core\sideloader\importers\Css\Css;
use core\view\Html;
use models\User\User;

Css::importDefault($this);
$request = App::getInstance()->getRequest();
$head = $this->getHead();

?><!DOCTYPE html>
<html lang="<?= $head->getLanguage()->code ?>">
<?= $head ?>

<script>
    /**
     * @param {Element} element
     */
    function adminPage_navItem(element) {
        element.addEventListener("click", () => {
            $('a', element)?.click();
            $('.target', element)?.click();
        });
    }
</script>

<body>
    <div class="root admin-page">
        <nav>
            <div class="start">
                <?= new AdminProject() ?>
                <?= AdminRouter::getInstance()->getMenu() ?>
            </div>

            <div class="end">
                <div class="nav-item" x-init="adminPage_navItem">
                    <span class="icon">
                        <?= Icon::nf('nf-fa-language') ?>
                    </span>

                    <?= $languageWindow = LanguageSelect::window(openButton: false) ?>
                    <div class="target" onclick="window_open($('#<?= $languageWindow->getId() ?>'))">
                        <?= $this->tr("Languages") ?>
                    </div>
                </div>

                <div class="nav-item" x-init="adminPage_navItem">
                    <span class="icon">
                        <?= Icon::nf('nf-fa-power_off', '<') ?>
                    </span>

                    <a href="<?= AdminLogin::createLogoutUrl($request->getUrl()) ?>">
                        <span><?= Html::escape($this->tr('Logout')) ?></span>
                        <span>(<?= Html::escape(User::fromRequest($request)->username) ?>)</span>
                    </a>
                </div>
            </div>

            <div
                class="resize-handle"
                data-target="<parent>"
                data-direction="horizontal"
            ></div>
        </nav>

        <main>
            <?= $this->view ?>
        </main>

        <?= Terminal::getInstance() ?>
    </div>
</body>
</html>