<?php /** @var AdminProject $this */

use components\Admin\AdminProject;
use core\admin\AdminRouter;
use core\App;
use core\view\Html;

?>
<?php $app = App::getInstance() ?>
<?php if (!is_null($project = $app->getProjectName())): ?>
    <div class="project">
        <h2>
            <a
                class="no-decoration"
                href="<?= $app->attach(AdminRouter::getInstance()->getPath()) ?>"
            >
                <?= Html::escape($project) ?>
            </a>
        </h2>
        <?php if (!is_null($author = $app->getProjectAuthor())): ?>
            <span class="author">
                <?php if (!is_null($authorLink = $app->getProjectAuthorLink())): ?>
                    <?= $this->tr('by') ?> <a
                        class="no-decoration"
                        href="<?= $authorLink ?>"
                        target="_blank"
                    >
                        <?= Html::escape($author) ?>
                    </a>
                <?php else: ?>
                    <?= $this->tr('by') ?> <?= Html::escape($author) ?>
                <?php endif; ?>
            </span>
        <?php endif; ?>
    </div>
<?php endif; ?>