<?php /** @var AdminProject $this */

use components\Admin\AdminProject;
use core\admin\AdminRouter;
use core\App;
use core\sideloader\importers\Css\Css;
use core\view\Html;

$app = App::getInstance();
Css::importDefault($this);

$router = is_null($this->dashboard)
    ? AdminRouter::getInstance()
    : $this->dashboard;

?><?php if (!is_null($project = $app->getProjectName())): ?>
    <div class="admin-project">
        <h2>
            <a
                class="no-decoration"
                href="<?= $app->attach($router->getPath()) ?>"
            >
                <?= Html::escape($project) ?>
            </a>
        </h2>

        <?php if (!is_null($author = $app->getProjectAuthor())): ?>
            <span class="author">
                <?php if (!is_null($authorLink = $app->getProjectAuthorLink())): ?>
                    <?= $this->tr('by') ?> <a
                        class="no-decoration"
                        href="<?= $authorLink ?>"
                        target="_blank"
                    >
                        <?= Html::escape($author) ?>
                    </a>
                <?php else: ?>
                    <?= $this->tr('by') ?> <?= Html::escape($author) ?>
                <?php endif; ?>
            </span>
        <?php endif; ?>
    </div>
<?php endif; ?>