<?php /** @var AdminFileSystemCreateDirectory $this */

use components\Admin\AdminFileSystemCreateDirectory;
use components\forms\Form;
use core\fs\FileServer;
use core\sideloader\importers\Javascript\Javascript;

Javascript::importDefault($this);

Form::importAssets();

?><button
    x-init="fs_mkdirButton_init"
    data-mkdir="<?= FileServer::getInstance()->createDirectoryUrl($this->directory) ?>"
>Create directory</button>