<?php /** @var Input $this */

use components\forms\controls\Input;
use core\view\Html;

$id = Html::escapeAttribute($this->getId());

?><div class="form-control <?= $this->cssClass ?>">
    <?php if (!empty($this->label)): ?>
        <label for="<?= $id ?>">
            <?= Html::escape($this->label) ?>
        </label>
    <?php endif; ?>
    <input
        type="<?= Html::escapeAttribute($this->type) ?>"
        value="<?= Html::escapeAttribute($this->value) ?>"
        name="<?= Html::escapeAttribute($this->name) ?>"
        id="<?= $id ?>"
        <?= $this->stringifyAttributes() ?>
    >
</div>
