<?php /** @var MultiSubmit $this */

use components\forms\controls\MultiSubmit;
use core\view\Html;

?><div class="form-actions">
    <?php foreach ($this->actions as $action): ?>
        <button
            type="<?= Html::escapeAttribute($action->getType()) ?>"
            <?php if (!is_null($action->getName())): ?>
                name="<?= Html::escapeAttribute($action->getName()) ?>"
                value="<?= Html::escapeAttribute($action->getValue()) ?>"
            <?php endif; ?>
            <?= $action->stringifyAttributes() ?>
        >
            <?= Html::escape($action->getLabel()) ?>
        </button>
    <?php endforeach; ?>
</div>
