<?php /** @var PasswordField $this */

use components\forms\controls\PasswordField;
use components\Icon;
use core\view\Html;

$id = Html::escapeAttribute($this->getId());

?><div
    class="form-control password <?= $this->cssClass ?>"
    x-init="form_password"
>
    <label for="<?= $id ?>">
        <?= Html::escape($this->getLabel()) ?>
    </label>

    <div class="password-container">
        <input
            type="password"
            value="<?= Html::escapeAttribute($this->getValue()) ?>"
            name="<?= Html::escapeAttribute($this->getFieldName()) ?>"
            id="<?= $id ?>"
            <?= $this->stringifyAttributes() ?>
            data-on-error="form_password_onError"
        >
        <?php if ($this->addVisibilityControl): ?>
            <div class="password-visibility-control">
                <button data-action="show">
                    <?= Icon::nf('nf-fa-eye', Html::escape($this->tr('Show'))) ?>
                </button>

                <button class="hide" data-action="hide">
                    <?= Icon::nf('nf-fa-eye_slash', Html::escape($this->tr('Hide'))) ?>
                </button>
            </div>
        <?php endif; ?>
    </div>
    <span class="hide form-invalid-message"></span>
</div>
