<?php /** @var TextArea $this */

use components\forms\controls\TextArea;
use core\view\Html;

$id = Html::escapeAttribute($this->getId());

?><div class="form-control <?= $this->cssClass ?>">
    <label for="<?= $id ?>">
        <?= Html::escape($this->label) ?>
    </label>

    <textarea
        id="<?= $id ?>"
        name="<?= Html::escapeAttribute($this->name) ?>"
        <?= $this->stringifyAttributes() ?>
    >
        <?= Html::escape($this->value) ?>
    </textarea>
</div>