<?php /** @var BreadCrumbs $this */

use components\layout\BreadCrumbs\BreadCrumbs;
use core\sideloader\importers\Css\Css;

Css::importDefault($this);

?><?php if (count($this->items) > 0): ?>
    <ul class="bread-crumbs">
        <?php $first = true; foreach ($this->items as $item): ?>
            <?php if (!$first && !is_null($this->delimitor)): ?>
                <li class="delimitor"><?= $this->delimitor ?></li>
            <?php endif; ?>

            <?= $item ?>
        <?php $first = false; endforeach; ?>
    </ul>
<?php endif; ?>
