<?php /** @var BreadCrumb $this */

use components\layout\BreadCrumbs\BreadCrumb;
use core\fs\FileSystem;
use core\utils\Arrays;

$label = $this->getLabel();

?><li class="bread-crumb">
    <?php if (is_null($this->getUrl())): ?>
        <span><?= $label ?></span>
    <?php else: ?>
        <button <?= Arrays::htmlEncode(FileSystem::createDirectoryLinkAttributes($this->getUrl())) ?>>
            <?= $label ?>
        </button>
    <?php endif; ?>
</li>
