<?php /** @var Article $this */

use components\Markdown\Markdown;
use components\pages\Article\Article;
use components\pages\Article\ArticleTemplate;
use core\sideloader\importers\Css\Css;
use core\sideloader\importers\Javascript\Javascript;
use core\view\Html;

Markdown::importAssets();
Javascript::importDefault($this);
Css::importDefault($this);

$language = $this->localization->getLanguage();

?><div class="page" x-init="article">
    <pre id="data-content" class="display-none"><?= Html::escape($this->content) ?></pre>

    <aside class="article-toc-wrapper">
        <div class="article-toc-container">
            <h3><?= Html::escape($this->tr("Table of Contents")) ?></h3>

            <div class="article-toc-content"></div>
        </div>

        <?php if (!empty($related = $this->page->getRelated())): ?>
            <div class="article-related-container column">
                <h3><?= Html::escape($this->tr("Related")) ?></h3>

                <div class="article-related-content column">
                    <?php foreach ($related as $page): ?>
                        <?= $page->getTemplate()->buildRelatedCard($page, $language) ?>
                    <?php endforeach; ?>
                </div>
            </div>
        <?php endif; ?>
    </aside>

    <article class="article">
        <div class="article-header column pad-gap">
            <div class="title">
                <h1><?= Html::escape($this->localization->title) ?></h1>

                <?php $description = $this->localization->getMeta()?->description ?>
                <?php if (!empty($description)): ?>
                    <p><?= Html::escape($description) ?></p>
                <?php endif; ?>
            </div>

            <?php if (!is_null($image = $this->page->getCoverImage()?->getFile())): ?>
                <img
                    class="article-cover-image"
                    src="<?= $image->getUrl(ArticleTemplate::getCoverTransformer()) ?>"
                    data-src-full="<?= $image->getUrl() ?>"
                    alt="Article cover image"
                >
            <?php endif; ?>
        </div>

        <section class="article-content"></section>
    </article>
</div>