<?php /** @var ToolBarItem $this */

use components\core\ToolBar\ToolBarItem;

?><?php if ($this->getMenuLevel() <= 1): ?>
    <span class="content"><?= $this->getLabel() ?></span>
<?php else: ?>
    <div
        class="dropdown-item"
        x-init="toolBar_item"
        data-action="<?= $this->action ?>"
        <?php if (!is_null($this->shortcut)): ?>
            data-shortcut="<?= $this->shortcut ?>"
        <?php endif; ?>
        <?= $this->stringifyAttributes() ?>
    >
        <span class="content"><?= $this->getLabel() ?></span>
        <?php if (!is_null($this->shortcut)): ?>
            <span class="hint"><?= $this->getShortcut() ?></span>
        <?php endif; ?>
    </div>
<?php endif; ?>
