<?php /** @var Head $this */

use components\FrontEndCore;
use components\Jsml;
use core\sideloader\SideLoader;
use core\view2\Head;
use core\view2\Html;

?><head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="icon" type="image/x-icon" href="<?= $this->getHtmlFavicon() ?>">

    <?php foreach ($this->getHtmlMeta() as $name => $content): ?>
        <meta
            name="<?= Html::escapeAttribute($name) ?>"
            content="<?= Html::escapeAttribute($content) ?>"
        >
    <?php endforeach; ?>

    <title>
        <?= Html::escape($this->getTitle()) ?>
    </title>

    <?= new FrontEndCore() ?>
    <?= Jsml::getInstance() ?>
    <?= SideLoader::getApi() ?>
    <?= SideLoader::getInstance() ?>

    <?php foreach ($this->getHtmlElements() as $element): ?>
        <?= $element ?>
    <?php endforeach; ?>
</head>