<?php /** @var Form $this */

use modules\forms\Form;
use modules\SideLoader\Javascript;

?>
<?php Javascript::import($this->getSource("form.js")); ?>
<form
    data-method="<?= $this->method ?>"
    <?php if (!is_null($this->action)): ?>
        action="<?= $this->action ?>"
    <?php endif; ?>
    onsubmit="submitForm(this); return false"
>
    <?php foreach ($this->controls as $control): ?>
        <?= $control->render() ?>
    <?php endforeach; ?>
</form>
