<?php /** @var RoutedMenuItem $this */

use components\layout\RoutedMenu\RoutedMenuItem;
use core\view\Html;

?><div class="item-label">
    <?php if (!is_null($this->icon)): ?>
        <span class="icon">
            <?= $this->icon ?>
        </span>
    <?php endif; ?>

    <?php if ($this->hasItem()): ?>
        <a href="<?= $this->createUrl() ?>">
            <?= Html::escape($this->tr($this->label)) ?>
        </a>
    <?php else: ?>
        <span>
            <?= Html::escape($this->tr($this->label)) ?>
        </span>
    <?php endif; ?>
</div>