<?php
/** @var AdminPhrasePacks $this */

use components\Admin\Phrase\AdminPhrasePacks;
use components\Icon;
use core\sideloader\importers\Css\Css;
use core\sideloader\importers\Javascript\Javascript;

Css::importDefault($this);
Javascript::importDefault($this);

// todo add breadcrumbs

?><div class="page-container">
    <div class="page-section">
        <div class="translation-header">
            <h1><?= $this->tr('Translation Packs') ?></h1>
            <p><?= $this->tr('Import existing translation packs or generate a new export package.') ?></p>
        </div>

        <div class="translation-grid">
            <section class="card">
                <div class="card-header row">
                    <div class="card-icon">
                        <?= Icon::nf('nf-fa-upload', '⬆') ?>
                    </div>

                    <h2><?= $this->tr('Import Translation Packs') ?></h2>
                </div>

                <p class="description">
                    <?= $this->trt('Upload a single translation pack {}', "<code>.json</code>") ?>
                    <?= $this->trt('or a {} archive containing multiple packs.', "<code>.zip</code>") ?>
                </p>

                <?= $this->createImportForm() ?>
            </section>

            <section class="card">
                <div class="card-header row">
                    <div class="card-icon">
                        <?= Icon::nf('nf-fa-download', '⬇') ?>
                    </div>

                    <h2><?= $this->tr('Export Translation Pack') ?></h2>
                </div>

                <p class="description"><?= $this->tr('Generate a translation package for a specific language.') ?></p>

                <?= $this->createExportForm() ?>
            </section>
        </div>
    </div>
</div>