<?php /** @var FileControl $this */

use components\core\fs\FileControl;
use components\core\Html\Html;
use components\core\Icon;
use core\sideloader\importers\Css\Css;
use core\sideloader\importers\Javascript\Javascript;
use models\core\fs\File;

Javascript::import($this->getResource('file-control.js'));
Css::import($this->getResource('file-control.css'));

$id = $this->getId();

?><div
    class="file-control <?= $this->cssClass ?>"
    x-init="form_fs_fileControl"
    data-control-id="<?= $id ?>"
    data-file-type="<?= $this->fileType ?>"
>
    <div class="form-control">
        <?php if (!is_null($this->label)): ?>
            <span class="control-label"><?= $this->label ?></span>
        <?php endif; ?>

        <input
            type="hidden"
            value="<?= $this->hash ?>"
            name="<?= $this->name ?>"
            id="<?= $id ?>"
            <?= $this->stringifyAttributes() ?>
        >

        <button class="select">
            <?= $this->tr('Select') ?>
        </button>
    </div>

    <?php $isFile = !is_null($this->file) ?>
    <?php $isTypeOfImage = $isFile && $this->file->isTypeOf(File::TYPE_IMAGE) ?>

    <div class="preview-image <?= $isTypeOfImage ? '' : 'display-none' ?>">
        <div class="file-preview image">
            <img
                src="<?= $this->file?->getUrl($this->getTransformer()) ?>"
                alt="Image preview"
            >
        </div>
    </div>

    <div class="preview-file <?= $isFile && !$isTypeOfImage ? '' : 'display-none' ?>">
        <div class="file-preview general">
            <div class="icon"><?= $this->file?->getEntryIcon() ?></div>
            <div class="details">
                <div class="name"><?= Html::escape($this->file?->getFileName()) ?></div>
                <div class="size"><?= Html::escape($this->file?->getHumanReadableSize()) ?></div>
            </div>
        </div>
    </div>

    <div class="preview-none <?= !$isFile ? '' : 'display-none' ?>">
        <div class="file-preview general">
            <div class="icon"><?= Icon::nf('nf-md-file_question', '?') ?></div>
            <div class="details">
                <div class="name">None</div>
                <div class="size">- B</div>
            </div>
        </div>
    </div>
</div>