<?php /** @var SubMenu $this */

use components\core\Admin\Menu\AdminMenu;
use components\core\Admin\SubMenu\SubMenu;

?>
<?php if (!$this->isEmpty()): ?>
    <div class="sub-menu <?= !$this->inset ? 'no-inset' : '' ?>">
        <?php foreach ($this->menu as $label => $menu): ?>
            <?php if ($label === AdminMenu::KEY_RENDER) continue; ?>
            <div>
                <?php if ($this->hasRender($label)): ?>
                    <a href="<?= $this->createUrl($label) ?>">
                        <?= $label ?>
                    </a>
                <?php else: ?>
                    <span><?= $label ?></span>
                <?php endif; ?>
                <div>
                    <?= new SubMenu($this->path .'/'. $label, $menu) ?>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
<?php endif; ?>
