<?php /** @var SubMenu $this */

use components\core\Admin\SubMenu\SubMenu;
use components\core\Icon;
use core\url\UrlGraph;

?>
<?php if (!$this->isEmpty()): ?>
    <div class="sub-menu <?= !$this->inset ? 'no-inset' : '' ?> <?= $this->isExpanded ? '' : 'hide' ?>">
        <?php foreach ($this->menu as $target => $menu): ?>
            <?php if ($target === UrlGraph::KEY_LEAF) continue; ?>
            <?php $subMenu = $this->createSubMenu($target) ?>
            <div
                class="menu-item <?= $subMenu->getCssClass() ?>"
            >
                <div class="head">
                    <?php if ($subMenu->hasRender()): ?>
                        <a href="<?= $this->createItemUrl($target) ?>">
                            <?= $this->segments->getSource($target) ?>
                        </a>
                    <?php else: ?>
                        <span><?= $this->segments->getSource($target) ?></span>
                    <?php endif; ?>

                    <?php if (!$subMenu->isEmpty()): ?>
                        <div class="dropdown-control">
                            <div class="<?= $subMenu->isExpanded ? 'hide' : '' ?>" data-action="show">
                                <?= Icon::nf('nf-fa-angle_right') ?>
                            </div>
                            <div class="<?= $subMenu->isExpanded ? '' : 'hide' ?>" data-action="hide">
                                <?= Icon::nf('nf-fa-angle_down') ?>
                            </div>
                        </div>
                    <?php endif; ?>
                </div>

                <?= $subMenu ?>
            </div>
        <?php endforeach; ?>
    </div>
<?php endif; ?>
