<?php /** @var ImageVariantPreview $this */

use core\sideloader\importers\Css\Css;
use core\sideloader\importers\Javascript\Javascript;

Javascript::importDefault($this);
Css::importDefault($this);

?><div class="image-variant-preview">
    <div
        class="preview"
        x-init="imageVariantPreview_preview"
        data-width-selector="<?= $this->widthSelector ?>"
        data-height-selector="<?= $this->heightSelector ?>"
    >
        <span class="size"></span>
    </div>
</div>