<?php /** @var ImageVariantPreview $this */

use components\fs\ImageVariantPreview;
use core\sideloader\importers\Css\Css;
use core\sideloader\importers\Javascript\Javascript;
use core\view\Html;

Javascript::importDefault($this);
Css::importDefault($this);

?><div class="image-variant-preview">
    <div
        class="preview"
        x-init="imageVariantPreview_preview"
        data-width-selector="<?= Html::escapeAttribute($this->widthSelector) ?>"
        data-height-selector="<?= Html::escapeAttribute($this->heightSelector) ?>"
    >
        <span class="size"></span>
    </div>
</div>