<?php /** @var AdminPageEditor $this */

use components\core\Admin\Page\AdminPageEditor;

?><section>
    <h1><?= $this->getTitle() ?></h1>

    <div class="row">
        <?php if (!is_null($this->model)): ?>
            <a href="<?= $this->getUrlToModel() ?>" target="_blank" class="button">
                <?= $this->tr('View on web') ?>
            </a>
        <?php endif; ?>

        <?php if ($this->model?->getTemplate()?->hasEditor() ?? false): ?>
            <a href="<?= $this->getTemplateEditorLink() ?>" target="_blank" class="button">
                <?= $this->tr('Edit page content') ?>
            </a>
        <?php endif; ?>
    </div>

    <?= $this->getForm() ?>
</section>
