<?php /** @var AdminMenuV2 $this */

use components\core\Admin\MenuV2\AdminMenuV2;
use components\core\Admin\SubMenuV2\SubMenuV2;
use modules\SideLoader\Css;

Css::import($this->getSource('admin-menu.css'));

?>
<div class="admin-menu no-inset sub-menu">
    <?php $menuV2 = new SubMenuV2($this->paths->getSegments(), '', $this->graph->getRoot()) ?>
    <?php $menuV2->inset($renderHome = $menuV2->hasRender() && !is_null($this->homeLabel)) ?>
    <?php if ($renderHome): ?>
        <a href="<?= $menuV2->createItemUrl() ?>">
            <?= $this->homeLabel->render() ?>
        </a>
    <?php endif; ?>
    <?= $menuV2->render() ?>
</div>
