<?php /** @var Form $this */

use components\forms\Form;
use core\view\Html;

Form::importAssets();

?><form
    class="form <?= $this->getCssClass() ?>"
    data-method="<?= Html::escapeAttribute($this->method) ?>"
    data-transformer="<?= $this->bodyTransformer ?>"
    <?php if (!is_null($this->action)): ?>
        action="<?= $this->action ?>"
    <?php endif; ?>
    <?= $this->stringifyAttributes() ?>
>
    <div class="form-barrier">
        <?php foreach ($this->elements as $control): ?>
            <?= $control ?>
        <?php endforeach; ?>
    </div>
</form>
